name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
    - name: Setup Node
      uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
